language: rust
sudo: false
rust:
- stable
- beta
- nightly

script:
- ./bootstrap.sh
- (cd quad-diesel && travis-cargo build)
- (cd quad-iron && travis-cargo build)
- (cd quad-rocket && travis-cargo --only nightly build)
