language: rust
sudo: false
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls

rust:
- stable
- beta
- nightly

# load travis-cargo
before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH

script:
- ./bootstrap.sh
- (cd quad-diesel && travis-cargo build)
- (cd quad-cli && travis-cargo build)
- (cd quad-iron && travis-cargo build)
- (cd quad-rocket && travis-cargo --only nightly build)
